# 베이스 이미지 설정
FROM node:14

# 작업 디렉토리 설정
WORKDIR /app

# npm 설치를 위한 설정 파일 복사
COPY frontend/package.json frontend/package-lock.json /app/

# npm 패키지 설치
RUN npm install

# 프로젝트 파일 복사
COPY frontend /app/

# 포트 설정 (React 기본 포트는 3000)
EXPOSE 3000

# React 애플리케이션 시작 명령
CMD ["npm", "start"]
