# Generated by Django 4.2.12 on 2024-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
