# Generated by Django 4.2.12 on 2024-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_message_recipient_deleted_message_sender_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="warning",
            field=models.BooleanField(default=False),
        ),
    ]
