# Generated by Django 4.2.12 on 2024-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
