# Generated by Django 4.2.12 on 2024-05-31 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_chatroom_name_alter_chatroom_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="blacklist_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="blacklist_user_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="max_members",
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
