# Generated by Django 4.2.12 on 2024-06-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatroom_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroommember",
            name="role",
            field=models.CharField(default="member", max_length=10),
        ),
        migrations.AddField(
            model_name="chatroommember",
            name="speaker",
            field=models.BooleanField(default=False),
        ),
    ]
