# Generated by Django 4.2.12 on 2024-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroommember_role_chatroommember_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='game_status',
            field=models.CharField(blank=True, choices=[('w', 'Wait'), ('s', 'Start')], max_length=2, null=True),
        ),
    ]
