version: '3.8'

services:
  backend:
    image: lsi3131/seta_backend:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env

  frontend:
    image: lsi3131/seta_frontend:latest
    ports:
      - "3000:3000"

