# Generated by Django 4.2.12 on 2024-05-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hits",
            field=models.IntegerField(default=0),
        ),
    ]
