# Generated by Django 4.2.12 on 2024-05-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_following'),
        ('post', '0002_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_mbti',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.mbti'),
        ),
    ]
