# Generated by Django 4.2.12 on 2024-05-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_comment_comment_mbti"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hot_post",
            field=models.BooleanField(default=False),
        ),
    ]
