# Generated by Django 4.2.12 on 2024-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_post_hot_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
