# Generated by Django 4.2.12 on 2024-05-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_mbti_user_mbti"),
    ]

    operations = [
        migrations.AddField(
            model_name="mbti",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
