# Generated by Django 4.2.12 on 2024-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
