# Generated by Django 4.2.12 on 2024-05-16 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                through="account.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
