# Generated by Django 4.2.12 on 2024-06-11 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MbtiVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_dimension', models.CharField(choices=[('IE', 'IE'), ('NS', 'NS'), ('FT', 'FT'), ('PJ', 'PJ')], max_length=2)),
                ('vote_value', models.CharField(choices=[('I', 'I'), ('E', 'E'), ('N', 'N'), ('S', 'S'), ('F', 'F'), ('T', 'T'), ('P', 'P'), ('J', 'J')], max_length=1)),
                ('mbti_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbti_votes_received', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbti_votes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'mbti_owner', 'vote_dimension')},
            },
        ),
    ]
