name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 트리거

jobs:
  deploy:
    runs-on: amazon-linux-2

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Execute deployment script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' < ~/deploy.sh
